// This file was generated by Prisma and assumes you have installed:
// npm install --save-dev prisma dotenv

import fs from "node:fs";
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Prefer a dedicated Prisma env file for migrations to avoid accidentally
// running migrations against production settings in .env.
const prismaEnvPath =
  process.env.PRISMA_ENV_PATH ??
  (fs.existsSync(path.join(process.cwd(), ".env.prisma")) ? ".env.prisma" : ".env");

dotenv.config({ path: prismaEnvPath });
// Prisma CLI may load `.env` automatically before this file runs; force the Prisma env file
// to win so migrations reliably target the intended database.
dotenv.config({ path: prismaEnvPath, override: true });

const databaseUrl =
  // Prefer a direct/non-pooler URL for Prisma migrations when available.
  process.env.DATABASE_PRIVATE_URL ??
  process.env.DATABASE_URL ??
  process.env.RAILWAY_DATABASE_URL;

if (!databaseUrl || !databaseUrl.trim()) {
  throw new Error(
    "Prisma migrations require a database URL. Set DATABASE_URL (or DATABASE_PRIVATE_URL) in the environment."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --use-system-ca prisma/seed.cjs",
  },
  datasource: {
    url: databaseUrl,
  },
});

